### PR TITLE
Fix #96 none handling for select and extend-select

### LINKED ISSUE #96: TypeError: argument of type 'NoneType' is not iterable
First of all, thanks for the plugin.

Recently I've found myself using flake8 HEAD, and it's changed a lot since the last release. Most importantly, [this fix](https://github.com/PyCQA/flake8/commit/367c810f0ebbca39146a037d3b6f82f139c9ebab) will break flake8-type-checking. This is a [similar issue](https://github.com/PyCQA/flake8-bugbear/issues/260) with flake8-bugbear.

### PR DESCRIPTION
**Pull request by wyuenho**
I'm not exactly sure if this is the best way to fix this issue, but this seems to be the only way to fix without haven't to rewrite a whole lot of tests.

### CODE REVIEW

**Comment by sondrelg** [comment]
Thanks for opening the issue and PR @wyuenho! Just so I can understand the issue properly, do you have a way for me to replicate the issue locally when on the flake8 main branch?

**Comment by wyuenho** [comment]
> do you have a way for me to replicate the issue locally 

Just install `flake8` HEAD and `flake8-type-checking` in any project, write a `.flake8` config without a `select` value, which is allowed, and that's it.

**Comment by sondrelg** [comment]
Running

```shell
deactivate \
  && rm -rf venv \
  && python3 -m venv venv --upgrade-deps \
  && source venv/bin/activate \
  && pip install git+https://github.com/pycqa/flake8@main flake8-type-checking \
  && echo "[flake8]\nexclude = .venv" > .flake8 \
  && echo "print('test')" > main.py \
  && flake8 .
```

I'm not able to replicate on Python 3.9. What's missing?

**Comment by wyuenho** [comment]
Ah ok, so for some reason this code path only gets hit when the file contains something like this:

```python
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator
```

I'm not entirely sure why...

**Comment by sondrelg** [comment]
Even with the example above I was not able to reproduce the issue yesterday. Would you be able to provide step-by-step instructions for how to replicate?

I'll get home from holidays tomorrow, and will have a bit more time available then. If you're able to provide replicating steps, I'll review and merge by Thursday most likely 👍  Thanks again for opening the PR!

**Comment by sondrelg** [comment]
After reviewing the PR, this seems sensible regardless of whether I'm able to replicate or not 🙂 Thanks!

**Pull request merged**
