### PR TITLE
feat: Support use of TYPE_CHECKING with simple boolean logic

### PR DESCRIPTION
**Pull request by steverice**
For various reasons, modules may be conditioned on multiple criteria that determine whether they should be imported. For example, if we have an module that should be imported during testing or type checking, we may do something like:
```python
if TYPE_CHECKING or environment == 'test':
    import foobar
```

Currently, the linter will flag the `foobar` import as needing to be moved into an `if TYPE_CHECKING` block in this scenario. This gives us two options, each of which is less than ideal. We could import the module twice, i.e.
```python
if TYPE_CHECKING:
    import foobar
elif environment == 'test':
    import foobar
```
or use a `# noqa` comment and lose the safety of the check when the code changes.

This commit adds some logic to handle these types of simple conditionals and determine if they are equivalent to `if TYPE_CHECKING:` for the purposes of this linter. In our simple example, we should be able to determine that `if TYPE_CHECKING or environment == 'test'` will always result in the module being imported if `TYPE_CHECKING` is True. Similarly, we should be able to determine that `if TYPE_CHECKING and environment == 'test'` is _not_ sufficient, since we have no guarantees about the value of `environment`.

### CODE REVIEW

**Comment by steverice** [comment]
It seems the 3.10.7 test workflow failed because of a network issue. Perhaps it can be retried.

**Comment by sondrelg** [comment]
Sorry @steverice, I think I saw the test failed when you posted this and assumed you'd make edits, then I missed your comment and forgot about it :bow: 

This looks good to me. Would you mind rebasing the PR and I'll take one final look at it before merging and releasing :+1:

**Comment by steverice** [comment]
Thanks @sondrelg , updated! I looked at the coverage report and it looks like the uncovered lines are from #103 and #126. Would you like me to add coverage for those?

**Comment by sondrelg** [comment]
If you're up for it, that would be amazing :clap:

**Comment by steverice** [comment]
@sondrelg #144 and #145 contain the fixes for the test coverage. Let's merge those first and then I'll rebase this.

Codecov is complaining on all three of these. Hopefully it's clear that this is due to the existing coverage issues, as a commit that only adds new tests can't possibly decrease coverage 😄

**Comment by sondrelg** [comment]
Thanks again :+1: Don't think you need to rebase this, I'll merge as is and release a new minor version shortly

**Pull request merged**
