### PR TITLE
chore: Drop Python 3.8 support. Add Python 3.13 support. Update CI/dev dependencies.

### PR DESCRIPTION
**Pull request by Daverball**
Might also be worth to move the mypy config from `setup.cfg` to `pyproject.toml`.

### CODE REVIEW

**Comment by Daverball** [comment]
I don't exactly know what causes it, but for some reason installing `flake8-use-pathlib` with some of the other updated dependencies breaks a small number tests in 3.12+

I decided to get rid of `flake8-use-pathlib` and instead use `flake8-bugbear` for the regression test. It technically should be a more reliable test, since it's a more complex plugin, accessing more nodes.

**Comment by Daverball** [comment]
@sondrelg The CodeCov issue is something you'd probably need to sort out yourself, by adding the `CODECOV_TOKEN` to the repository secrets and passing it to the codecov action, they recently started requiring a token, even for open source projects.

**Comment by Daverball** [comment]
Actually nevermind, looks like you are already supplying it, but it's not being used for PRs

Maybe `fail_ci_if_error` should be `false` for PRs.

**Review by sondrelg — APPROVED** [review]
Nice! Feel free to move the mypy config too 👍

**Pull request merged**
